### ISSUE TITLE
unable to use `lcov` for Coveralls.io report

### ISSUE THREAD

**Issue by spencerlepine** [spencerlepine/woofer#43]
### Ticket: Trello Ticket [#100](https://trello.com/c/cHlD0RCW)

GitHub Actions CD/CI pipeline does not use Coveralls.io report anymore. Server/Client folder have separate coverage reports.
Need to update Node CI workflow to handle `lcov` files, merge the files, then upload to Coveralls.io again.

## PROBLEM:
Does not merge `lcov` files properly? Reporting 0% coverage...

### Checklist:
- [x] Upload lcov reports to artifacts in GitHub Actions
- [x] Uncomment Coveralls step, upload lcov report to Coveralls.io
- [x] Merge lcov reports in final coverage job BROKEN

## USE THIS NOW:
Use [Codecov](https://github.com/codecov/codecov-action):
```yml
- uses: codecov/codecov-action@v2
  with:
    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
```

REMOVE TIHS:
```yml
 coverage_comment:
  #   name: Coverage Upload
  #   permissions:
  #     checks: write
  #     pull-requests: write
  #   needs: [client_test, server_test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: "⬇️ Download the client test coverage report"
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: client-coverage

  #     - name: "📜 Copy the client coverage file"
  #       run: |
  #         mv coverage-final.json client-coverage-final.json
  #     - name: "⬇️ Download the server test coverage report"
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: server-coverage

  #     - name: "📜 Copy the server coverage file"
  #       run: |
  #         mv coverage-final.json server-coverage-final.json
  #     - name: "🔧 Set up Node"
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}

  #     - name: "🔀 Merge the coverage reports"
  #       run: npx istanbul-merge --out coverage-final.json ./client-coverage-final.json ./server-coverage-final.json

  #     - name: "⬆️ Comment test coverage report"
  #       uses: AthleticNet/comment-test-coverage@1.1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         path: ./coverage-final.json
  #         title: Woofer Test Coverage

  coverage_upload:
    name: Coverage Coveralls.io Upload
    needs: [client_test, server_test]
    runs-on: ubuntu-latest
```

**Comment by spencerlepine** [comment]
## USE THIS NOW:
Use [Codecov](https://github.com/codecov/codecov-action):
```yml
- uses: codecov/codecov-action@v2
  with:
    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
```

**Comment by spencerlepine** [comment]
Create `codecov.yml` in root dir:
```yml

   
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

coverage:
  range: "70..100"
  round: down
  precision: 2
  status:
    project:
      default:
        # basic
        target: 60%
        threshold: 0%
        # advanced settings
        if_ci_failed: error
        informational: false
        only_pulls: false
```

**Comment by spencerlepine** [comment]
## Solution:
> Sign up for [Codacy](https://www.codacy.com/)
> Save `CODACY_PROJECT_TOKEN`

Test and Report Coverage
```yml
 - name: "✅  Run tests"
        working-directory: ${{ env.working-directory }}
        run: npm run test -- --coverage

      - name: "📁 Upload server test coverage artifact"
        uses: actions/upload-artifact@v3
        with:
          name: server-coverage-file-${{ github.sha }}
          path: ${{ env.working-directory }}/coverage/lcov.info
          retention-days: 3
```

Download the artifacts, upload to Codacy
```yml
coverage_upload:
    needs: [server_test, client_test]
    runs-on: ubuntu-latest
    environment: CI
    name: Codacy Upload

    steps:
      - name: "⬇️ Download the client test coverage lcov report"
        uses: actions/download-artifact@v3
        with:
          name: client-coverage-file-${{ github.sha }}

      - name: "📜 Copy the client lcov coverage file"
        run: |
          mv lcov.info client-lcov.info
      - name: "⬇️ Download the server test coverage lcov report"
        uses: actions/download-artifact@v3
        with:
          name: server-coverage-file-${{ github.sha }}

      - name: "📜 Copy the server lcov coverage file"
        run: |
          mv lcov.info server-lcov.info

      - name: "🌪️ Publish to Codacy"
        run: |
          export CODACY_PROJECT_TOKEN="${{ secrets.CODACY_PROJECT_TOKEN }}"
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Javascript -r client-lcov.info -r server-lcov.info
```
