### ISSUE TITLE
replace with Nimbella Deployment

### ISSUE THREAD

**Issue by spencerlepine** [spencerlepine/woofer#54]
> TOREAD: Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests - [Article](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
> TOREAD: Keeping your GitHub Actions and workflows secure Part 2: Untrusted input - [Article](https://securitylab.github.com/research/github-actions-untrusted-input/)
> TOREAD: How to Hide Sensitive Things in GitHub Actions Logs - [Article](https://www.tutorialworks.com/github-actions-mask-url/)
> TOREAD: How We Discovered Vulnerabilities in CI/CD Pipelines of Popular Open-Source Projects - [Article](https://cycode.com/blog/github-actions-vulnerabilities/)

### GitHub Actions (CD) Deployment addition

Nimbella GitHub Actions - [Example Repository](https://github.com/bolt-hub/github-ci-cd-nimbella-shortener)

## Checklist Repo
- [x] READ: GitHub Actions CI/CD Pipeline - [Nimbella Article](https://nimbella.com/blog/ci/cd-pipeline-with-github-actions)
- [ ] READ: Nimbella Guide to Serverless - [Blog Post](https://nimbella.com/blog/no-infrastructure-just-code-learn-the-simplicity-of-serverless)
- [ ] READ: How to Migrate from Containers to Nimbella Serverless Architecture- [Blog Post](https://nimbella.com/blog/how-to-migrate-from-containers-to-nimbella-serverless-architecture)
- [ ] Create a Nimbella Account -> [Nimbella Account](https://nimbella.com/signup)
- [ ] install nim CLI -> [Nimbella Install Docs](https://docs.nimbella.com/install)
- [ ] create ${{ secrets.DEPLOYER_LOGIN_TOKEN }} in production enviroment
- [ ] add secret to EXAMPLE REPOSITORY secrets
- [ ] create `project.yml` nimbella config file in <rootDir>
```yml
bucket:
  strip: 1

packages:
   - name: s
     actions:
      - name: url
        limits:
          timeout: 60000
        environment:
          DB_Username: ${DB_Username}
          DB_Password: ${DB_Password}
          DB_ClusterUri: ${DB_ClusterUri}
          DB_Name: ${DB_Name}
          BASE_URL: ${BASE_URL}
```
- [ ] Add `nimbella` deployment to deploy workflow
```yml
       - name: "🔧 Create .env file"
        run: |
          rm -f .env
          echo ${{ secrets.ENV_PRODUCTION }} > .env
          cp .env ./client/.env

                                #Install Nim CLI
      - run: npm install -g https://apigcp.nimbella.io/downloads/nim/nimbella-cli.tgz
      - run: nim auth login ${{ secrets.DEPLOYER_LOGIN_TOKEN }} #Login Nim CLI
      - run: nim project deploy . #Deploy Project Artifacts on Nimbella
```

## MORE:
Broken Docs Page: [sample-project-walkthrough](https://docs.nimbella.com/sample-project-walkthrough)
Broken Nimbella Docs MARKDOWN File => [Nimbella Doc Article](https://github.com/nimbella/docs/blob/master/docs/sample-project.md)
